GET http://localhost:3001/api/persons/
###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
  "title": "Your title here",
  "content": "Your content here"
}
###
DELETE http://localhost:3001/api/persons/4
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Dan Abramova",
  "number": "345344343545"
}